# Generated by Django 5.2.8 on 2025-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_contactmessage_memberapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorapplication',
            name='tier',
            field=models.CharField(blank=True, choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('bronze', 'Bronze'), ('partner', 'Partner'), ('other', 'Other')], max_length=20),
        ),
    ]
