# Generated by Django 5.2.7 on 2025-11-04 21:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('partner', 'Partner')], default='bronze', max_length=10)),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
