# Generated by Django 5.2.8 on 2025-11-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='type',
            field=models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('bronze', 'Bronze'), ('partner', 'Partner')], default='bronze', max_length=10),
        ),
    ]
